version: "3"    
services:
  app:
    image: app:0.2
    build: .
    command: "node /home/newapp/app.js"
    ports:
      - "3003:3003"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    depends_on:
    - mongodb
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_SERVER=mongodb
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
volumes:
  mongo-data:
    driver: local 


